export const PAYMENT_REPOSITORY = Symbol("PAYMENT_REPOSITORY");
export const PAYMENT_PROVIDER = Symbol("PAYMENT_PROVIDER");
export const PAYMENT_WEBHOOK_EVENT_REPOSITORY = Symbol(
  "PAYMENT_WEBHOOK_EVENT_REPOSITORY",
);
