apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secret
  labels:
    app.kubernetes.io/name: billing-service
    app.kubernetes.io/part-of: fiap-tech-challenge
type: Opaque
stringData:
  JWT_SECRET: "replace-with-auth-function-jwt-secret"
  MONGODB_URI: "replace-with-billing-mongodb-atlas-uri"
  MERCADO_PAGO_TEST_ACCESS_TOKEN: "replace-with-test-access-token"
  MERCADO_PAGO_TEST_WEBHOOK_SECRET: "replace-with-test-webhook-secret"
