apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secret
  labels:
    app.kubernetes.io/name: billing-service
    app.kubernetes.io/part-of: fiap-tech-challenge
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  MONGODB_URI: "${BILLING_MONGODB_URI}"
  MERCADO_PAGO_TEST_ACCESS_TOKEN: "${MERCADO_PAGO_TEST_ACCESS_TOKEN}"
  MERCADO_PAGO_TEST_WEBHOOK_SECRET: "${MERCADO_PAGO_TEST_WEBHOOK_SECRET}"
